### ISSUE TITLE
opt downloadで--endを必須にする

### ISSUE THREAD

**Issue by Mishima-Ryuji** [opthub-org/opthub-client#91]
こちらdefaultをNoneにして、Noneの場合は最後の試行までダウンロードするようにできますか。

_Originally posted by @Mishima-Ryuji in https://github.com/opthub-org/opthub-client/pull/77#discussion_r1660088031_

**Comment by tkumamoto** [comment]
end を必須にして、動かすように変更
それに合わせてドキュメントも変更
